use_frameworks!

platform :ios, '8.0'

target 'HTJExtension_Example' do
  pod 'HTJExtension', :path => '../'

#  target 'HTJExtension_Tests' do
#    inherit! :search_paths
#
#    #pod 'Specta'
#    #pod 'Expecta'
#  end
end
